### ISSUE TITLE
Separate column for website link

### ISSUE THREAD

**Issue by ghost** [ObjectifGroup/helplouisiana#1]
In the table of resources, would it be appropriate to have a separate field for websites alongside the telephone number? 

The flooding has damaged a lot of critical infrastructure, including mobile networks in some areas, meaning Wi-Fi and the internet is a lot better in terms of access at the moment. I just think we need to make it clearer that it's a link to the web site rather than a note, per se.

Let me know what you reckon

**Comment by edireson** [comment]
Good call; I was originally trying to minimize horiz space usage, but #2 makes life better on that front.
