### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by ghost** [ObjectifGroup/helplouisiana#3]
I have an RDS database set up on Amazon Web Services for the old web site if you want access to that for storing and retrieving resources?

**Comment by edireson** [comment]
Right now it's just served via S3/Cloudfront, so there isn't a processing language to exist with a database. (Although I suppose it could be done via JS?)

Anyhow, happy to accept a PR that enables this - but I don't have the bandwidth right now to incorporate.

**Comment by ghost** [comment]
I could create some form of API on my current EC2 instance to serve JSON and pick it up in Javascript using Ajax.

I'm quite busy at the moment with school but I'll chuck something together in due course.
